spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forcutbook
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size : 100

  jackson:
    time-zone: Asia/Seoul

aws:
  s3:
    accessKeyId : ${AWS_ACCESS_KEY_ID}
    secretAccessKey : ${AWS_SECRET_ACCESS_KEY}
    bucketName : forcutbook-diary-images
    imageUrlPrefix : https://forcutbook-diary-images.s3.ap-northeast-2.amazonaws.com/