spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forcutbook
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size : 100

  jackson:
    time-zone: Asia/Seoul

aws:
  s3:
    accessKeyId : ${AWS_ACCESS_KEY_ID}
    secretAccessKey : ${AWS_SECRET_ACCESS_KEY}
    bucketName : forcutbook-diary-images
    imageUrlPrefix : https://forcutbook-diary-images.s3.ap-northeast-2.amazonaws.com/

hugging-face:
  api:
    key: ${HUGGING_FACE_API_KEY}

clova:
  studio:
    host : https://clovastudio.stream.ntruss.com
    apiKey: ${CLOVA_API_KEY}
    apiKeyPrimaryVal : ${CLOVA_API_KEY_PRIMARY_VAL}


---

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
#              - account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정